#!/bin/bash

#sshfs varpe8@users.itk.ppke.hu:public_html /home/itep/Dokumentumok/Suli/suliHonlap/szero

#cp -a -u $1/ szero/ #2>/dev/null

#find szero/ -type d -exec chmod 755 {} \;
#find szero/ -type f -exec chmod 644 {} \;

#fusermount -u /home/itep/Dokumentumok/Suli/suliHonlap/szero

scp -r $1 varpe8@users.itk.ppke.hu:public_html 
